### ISSUE TITLE
立刻star!!

### ISSUE THREAD

**Issue by fei0319** [gaokao-team/GaokaoNote#1]
非常感谢您能够开放如此珍贵无价的学习资料，这就全文背诵。orz Clouder!

**Comment by Clouder0** [comment]
您何不赶快加入/se/se

**Comment by fei0319** [comment]
> 
> 
> 您何不赶快加入/se/se

没有手机，注册不了teambition/kk

**Comment by Clouder0** [comment]
> > 您何不赶快加入/se/se
> 
> 没有手机，注册不了teambition/kk

/yun 您可以找父母借用一下

**Comment by fei0319** [comment]
> 
> 
> > > 您何不赶快加入/se/se
> > 
> > 
> > 没有手机，注册不了teambition/kk
> 
> /yun 您可以找父母借用一下

晚上整一下
